baseURL = 'https://rafalole.github.io/dea-web/'
defaultContentLanguage = 'pl'
defaultContentLanguageInSubdir = false
title = 'DeaPrint - Profesjonalne Usługi Fotograficzne'

[build]
  writeStats = true

[languages]
  [languages.pl]
    title = 'DeaPrint - Profesjonalne Usługi Fotograficzne'
    weight = 1
    languageName = 'Polski'
    [languages.pl.params]
      description = 'Profesjonalne usługi fotograficzne w Wrocławiu. Zdjęcia dokumentów, wydruki fotograficzne, albumy, kalendarze.'
  
  [languages.en]
    title = 'DeaPrint - Professional Photography Services'
    weight = 2
    languageName = 'English'
    [languages.en.params]
      description = 'Professional photography services in Wrocław. Document photography, photo prints, albums, calendars.'
  
  [languages.ukr]
    title = 'DeaPrint - Професійні Фотопослуги'
    weight = 3
    languageName = 'Українська'
    [languages.ukr.params]
      description = 'Професійні фотопослуги у Вроцлаві. Фотографування документів, фотодруки, альбоми, календарі.'

[params]
  company = 'DeaPrint'
  owner = 'Kasia'
  address = 'Warmińska 20/47, 54-110 Wrocław'
  phone = '882947647'
  email = 'deaprint.kasia@gmail.com'
  
[menu]
  [[menu.main]]
    name = 'Strona główna'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Usługi'
    url = '/services/'
    weight = 2
  [[menu.main]]
    name = 'Galeria'
    url = '/gallery/'
    weight = 3
  [[menu.main]]
    name = 'Cennik'
    url = '/pricing/'
    weight = 4
  [[menu.main]]
    name = 'Kontakt'
    url = '/contact/'
    weight = 5
